// ─── Font stacks ──────────────────────────────────────────────────────────────
// SERIF_ELEGANT  → Playfair Display — Diwali, Eid, Christmas, Good Friday, Buddha
// SERIF_CINZEL   → Cinzel — Republic Day, Independence Day, Mahavir, Gurpurab
// DISPLAY_SCRIPT → Dancing Script — Raksha Bandhan, Onam, Pongal
// DISPLAY_BOLD   → Bebas Neue — New Year, Hackathon, Product Launch
// SERIF_FRAUNCES → Fraunces — Holi, Navratri, Dussehra, Ganesh Chaturthi, Lohri, Baisakhi
// SANS_INTER     → Inter — event announcements, fallback

export const FONT_STACKS = {
  SERIF_ELEGANT:  "'Playfair Display', Georgia, 'Times New Roman', serif",
  SERIF_CINZEL:   "'Cinzel', 'Palatino Linotype', Georgia, serif",
  DISPLAY_SCRIPT: "'Dancing Script', cursive",
  DISPLAY_BOLD:   "'Bebas Neue', 'Impact', 'Arial Narrow', sans-serif",
  SERIF_FRAUNCES: "'Fraunces', Georgia, serif",
  SANS_INTER:     "'Inter', 'Segoe UI', system-ui, sans-serif",
};

// Festival Wishes Templates
export const festivalWishTemplates = [
  {
    id: 'diwali',
    name: 'Diwali',
    festival: 'Diwali',
    // Full-poster design tokens
    posterBg: 'linear-gradient(160deg, #0D1B3E 0%, #1A2A5E 45%, #0D1B3E 100%)',
    headerStyle: 'none',          // no purple strip — festival owns the bg
    accentColor: '#F5C518',
    accentColor2: '#FF6B00',
    textColor: '#F5C518',
    bodyTextColor: '#E8D5A3',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '52px',
    headlineWeight: '800',
    headlineEffect: 'gold-glow',  // used by canvas renderer
    secondaryColor: '#FF6B00',
    motif: 'diwali',
    headline: 'Happy Diwali',
    defaultMessage: 'Wishing you and your loved ones a festival full of light, joy, and prosperity. May this Diwali illuminate your life with happiness and success.',
  },
  {
    id: 'holi',
    name: 'Holi',
    festival: 'Holi',
    posterBg: '#FFFDF5',
    headerStyle: 'none',
    accentColor: '#FF1493',
    accentColor2: '#FFD700',
    textColor: '#C0006A',
    bodyTextColor: '#3A2A00',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '58px',
    headlineWeight: '900',
    headlineEffect: 'multicolor',
    secondaryColor: '#00CED1',
    motif: 'holi',
    headline: 'Happy Holi',
    defaultMessage: 'May the colours of Holi fill your life with joy, laughter, and endless happiness. Wishing you a vibrant and colourful celebration!',
  },
  {
    id: 'eid-ul-fitr',
    name: 'Eid-ul-Fitr',
    festival: 'Eid-ul-Fitr',
    posterBg: 'linear-gradient(160deg, #0A3D2E 0%, #145A3C 50%, #0A3D2E 100%)',
    headerStyle: 'none',
    accentColor: '#D4AF37',
    accentColor2: '#F0D060',
    textColor: '#F0D060',
    bodyTextColor: '#C8E6D0',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '48px',
    headlineWeight: '700',
    headlineEffect: 'gold-serif',
    secondaryColor: '#D4AF37',
    motif: 'eid',
    headline: 'Eid Mubarak',
    defaultMessage: 'May this auspicious occasion of Eid bring peace, happiness, and prosperity to you and your family. Eid Mubarak!',
  },
  {
    id: 'eid-al-adha',
    name: 'Eid-al-Adha',
    festival: 'Eid-al-Adha',
    posterBg: 'linear-gradient(160deg, #0A3D2E 0%, #145A3C 50%, #0A3D2E 100%)',
    headerStyle: 'none',
    accentColor: '#C9A84C',
    accentColor2: '#E8C870',
    textColor: '#E8C870',
    bodyTextColor: '#C8E6D0',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '42px',
    headlineWeight: '700',
    headlineEffect: 'gold-serif',
    secondaryColor: '#C9A84C',
    motif: 'eid',
    headline: 'Eid al-Adha Mubarak',
    defaultMessage: 'On this blessed occasion of Eid al-Adha, may Allah bless you with happiness, peace, and prosperity. Wishing you and your family a joyful celebration.',
  },
  {
    id: 'christmas',
    name: 'Christmas',
    festival: 'Christmas',
    posterBg: 'linear-gradient(170deg, #F8FFF8 0%, #EEF8EE 40%, #FFF5F5 100%)',
    headerStyle: 'none',
    accentColor: '#B31B1B',
    accentColor2: '#1B5E20',
    textColor: '#B31B1B',
    bodyTextColor: '#2A3A2A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '50px',
    headlineWeight: '800',
    headlineEffect: 'christmas-red',
    secondaryColor: '#1B5E20',
    motif: 'christmas',
    headline: 'Merry Christmas',
    defaultMessage: 'Wishing you the warmth of family, the joy of friends, and the best of everything this Christmas and throughout the coming year.',
  },
  {
    id: 'new-year',
    name: 'New Year',
    festival: 'New Year',
    posterBg: 'linear-gradient(160deg, #020818 0%, #081535 50%, #020818 100%)',
    headerStyle: 'none',
    accentColor: '#FFD700',
    accentColor2: '#C0C0C0',
    textColor: '#FFD700',
    bodyTextColor: '#C8D8F0',
    fontStack: "'Bebas Neue', 'Impact', sans-serif",
    headlineFontSize: '72px',
    headlineWeight: '400',
    headlineEffect: 'gold-glow',
    secondaryColor: '#C0C0C0',
    motif: 'newyear',
    headline: 'Happy New Year',
    defaultMessage: 'Cheers to new beginnings, bigger dreams, and brighter days ahead. Wishing you a wonderful New Year filled with joy and success!',
  },
  {
    id: 'independence-day',
    name: 'Independence Day',
    festival: 'Independence Day',
    posterBg: 'linear-gradient(180deg, #FF9933 0%, #FF9933 22%, #FFFFFF 22%, #FFFFFF 44%, #138808 44%, #138808 66%, #FFFFFF 66%, #FFFFFF 78%, #000080 78%, #000080 100%)',
    headerStyle: 'none',
    accentColor: '#FF9933',
    accentColor2: '#138808',
    textColor: '#000080',
    bodyTextColor: '#1A1A1A',
    fontStack: "'Cinzel', Georgia, serif",
    headlineFontSize: '40px',
    headlineWeight: '800',
    headlineEffect: 'tricolour',
    secondaryColor: '#138808',
    motif: 'independence',
    headline: 'Happy Independence Day',
    defaultMessage: 'Wishing you a proud and joyful Independence Day. Let us honour the spirit of freedom and unity that defines our great nation.',
  },
  {
    id: 'republic-day',
    name: 'Republic Day',
    festival: 'Republic Day',
    posterBg: 'linear-gradient(160deg, #F8F4E8 0%, #FFFDF0 60%, #F0F8F0 100%)',
    headerStyle: 'none',
    accentColor: '#FF9933',
    accentColor2: '#138808',
    textColor: '#000080',
    bodyTextColor: '#1A1A1A',
    fontStack: "'Cinzel', Georgia, serif",
    headlineFontSize: '38px',
    headlineWeight: '800',
    headlineEffect: 'tricolour',
    secondaryColor: '#138808',
    motif: 'republic',
    headline: 'Happy Republic Day',
    defaultMessage: 'On this day we celebrate the strength of our democracy and the values enshrined in our Constitution. Happy Republic Day!',
  },
  {
    id: 'raksha-bandhan',
    name: 'Raksha Bandhan',
    festival: 'Raksha Bandhan',
    posterBg: 'linear-gradient(160deg, #FFF0F5 0%, #FFF8F0 50%, #FFF0F5 100%)',
    headerStyle: 'none',
    accentColor: '#D4607A',
    accentColor2: '#E8A030',
    textColor: '#8B1A35',
    bodyTextColor: '#3A1A1A',
    fontStack: "'Dancing Script', cursive",
    headlineFontSize: '54px',
    headlineWeight: '700',
    headlineEffect: 'rose-gold',
    secondaryColor: '#E8A030',
    motif: 'rakhi',
    headline: 'Happy Raksha Bandhan',
    defaultMessage: 'May the bond of love, care, and protection between brothers and sisters grow stronger with every passing year. Happy Raksha Bandhan!',
  },
  {
    id: 'ganesh-chaturthi',
    name: 'Ganesh Chaturthi',
    festival: 'Ganesh Chaturthi',
    posterBg: 'linear-gradient(160deg, #FF8C00 0%, #FFA020 30%, #FFD050 70%, #FF8C00 100%)',
    headerStyle: 'none',
    accentColor: '#8B0000',
    accentColor2: '#FFD700',
    textColor: '#3B0000',
    bodyTextColor: '#3B0000',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '42px',
    headlineWeight: '900',
    headlineEffect: 'saffron-dark',
    secondaryColor: '#FFD700',
    motif: 'ganesh',
    headline: 'Happy Ganesh Chaturthi',
    defaultMessage: 'May Lord Ganesha bless you with wisdom, prosperity, and the removal of all obstacles from your path. Ganpati Bappa Morya!',
  },
  {
    id: 'dussehra',
    name: 'Dussehra',
    festival: 'Dussehra',
    posterBg: 'linear-gradient(160deg, #FF6B00 0%, #FF8C00 40%, #FFB020 100%)',
    headerStyle: 'none',
    accentColor: '#8B0000',
    accentColor2: '#FFD700',
    textColor: '#3B0000',
    bodyTextColor: '#3B0000',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '52px',
    headlineWeight: '900',
    headlineEffect: 'dark-on-orange',
    secondaryColor: '#FFD700',
    motif: 'dussehra',
    headline: 'Happy Dussehra',
    defaultMessage: 'May this Dussehra mark the victory of good over evil in your life. Wishing you strength, courage, and triumph in everything you do.',
  },
  {
    id: 'navratri',
    name: 'Navratri',
    festival: 'Navratri',
    posterBg: 'linear-gradient(135deg, #CC0066 0%, #FF3385 25%, #FF6B00 50%, #FFD700 75%, #CC0066 100%)',
    headerStyle: 'none',
    accentColor: '#FFFFFF',
    accentColor2: '#FFD700',
    textColor: '#FFFFFF',
    bodyTextColor: '#FFF0E8',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '54px',
    headlineWeight: '900',
    headlineEffect: 'white-on-vivid',
    secondaryColor: '#FFD700',
    motif: 'navratri',
    headline: 'Happy Navratri',
    defaultMessage: 'May Goddess Durga bless you with her divine grace, strength, and happiness during this auspicious festival. Happy Navratri!',
  },
  {
    id: 'onam',
    name: 'Onam',
    festival: 'Onam',
    posterBg: 'linear-gradient(160deg, #E8F5E9 0%, #F1FBF1 50%, #E8F5E9 100%)',
    headerStyle: 'none',
    accentColor: '#1B5E20',
    accentColor2: '#FFD700',
    textColor: '#1B5E20',
    bodyTextColor: '#1A3A1A',
    fontStack: "'Dancing Script', cursive",
    headlineFontSize: '58px',
    headlineWeight: '700',
    headlineEffect: 'kerala-green',
    secondaryColor: '#FFD700',
    motif: 'onam',
    headline: 'Happy Onam',
    defaultMessage: 'Wishing you the blessings of prosperity, peace, and happiness on this harvest festival. May Onam bring joy and togetherness!',
  },
  {
    id: 'pongal',
    name: 'Pongal',
    festival: 'Pongal',
    posterBg: 'linear-gradient(160deg, #FFF8DC 0%, #FFFACD 50%, #FFF3AA 100%)',
    headerStyle: 'none',
    accentColor: '#8B4513',
    accentColor2: '#FF6B00',
    textColor: '#6B2800',
    bodyTextColor: '#3A1A00',
    fontStack: "'Dancing Script', cursive",
    headlineFontSize: '58px',
    headlineWeight: '700',
    headlineEffect: 'harvest-brown',
    secondaryColor: '#FF6B00',
    motif: 'pongal',
    headline: 'Happy Pongal',
    defaultMessage: 'On this auspicious harvest festival, may your life overflow with joy, abundance, and good fortune. Wishing you a very Happy Pongal!',
  },
  {
    id: 'baisakhi',
    name: 'Baisakhi',
    festival: 'Baisakhi',
    posterBg: 'linear-gradient(160deg, #FFF8DC 0%, #FFFACD 40%, #E8F5E9 100%)',
    headerStyle: 'none',
    accentColor: '#8B4513',
    accentColor2: '#1B5E20',
    textColor: '#5C2800',
    bodyTextColor: '#2A1A00',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '54px',
    headlineWeight: '900',
    headlineEffect: 'wheat-gold',
    secondaryColor: '#1B5E20',
    motif: 'baisakhi',
    headline: 'Happy Baisakhi',
    defaultMessage: 'May the harvest festival of Baisakhi bring you prosperity, happiness, and the spirit of celebration. Wishing you a joyful Baisakhi!',
  },
  {
    id: 'lohri',
    name: 'Lohri',
    festival: 'Lohri',
    posterBg: 'linear-gradient(160deg, #1A0A00 0%, #3D1A00 40%, #1A0A00 100%)',
    headerStyle: 'none',
    accentColor: '#FF4500',
    accentColor2: '#FFD700',
    textColor: '#FFD700',
    bodyTextColor: '#FFB87A',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '56px',
    headlineWeight: '900',
    headlineEffect: 'fire-glow',
    secondaryColor: '#FFD700',
    motif: 'lohri',
    headline: 'Happy Lohri',
    defaultMessage: 'May the warmth of the Lohri bonfire fill your life with happiness, love, and good health. Wishing you and your family a wonderful Lohri!',
  },
  {
    id: 'gurpurab',
    name: 'Gurpurab',
    festival: 'Gurpurab',
    posterBg: 'linear-gradient(160deg, #1A0A00 0%, #3D1800 30%, #7A3800 60%, #3D1800 100%)',
    headerStyle: 'none',
    accentColor: '#FFD700',
    accentColor2: '#FF8C00',
    textColor: '#FFD700',
    bodyTextColor: '#FFD0A0',
    fontStack: "'Cinzel', Georgia, serif",
    headlineFontSize: '46px',
    headlineWeight: '600',
    headlineEffect: 'gold-glow',
    secondaryColor: '#FF8C00',
    motif: 'gurpurab',
    headline: 'Happy Gurpurab',
    defaultMessage: 'On this sacred occasion of Gurpurab, may the teachings of Guru Nanak Dev Ji inspire you to live a life of compassion, service, and devotion. Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh!',
  },
  {
    id: 'good-friday',
    name: 'Good Friday',
    festival: 'Good Friday',
    posterBg: 'linear-gradient(160deg, #2A1A3E 0%, #3D2855 50%, #2A1A3E 100%)',
    headerStyle: 'none',
    accentColor: '#C8A8D8',
    accentColor2: '#FFFFFF',
    textColor: '#E8D8F8',
    bodyTextColor: '#D0C0E8',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '46px',
    headlineWeight: '700',
    headlineEffect: 'lavender-glow',
    secondaryColor: '#FFFFFF',
    motif: 'goodfriday',
    headline: 'Good Friday',
    defaultMessage: 'On this solemn day, may you find peace, reflection, and hope. Wishing you a meaningful Good Friday.',
  },
  {
    id: 'buddha-purnima',
    name: 'Buddha Purnima',
    festival: 'Buddha Purnima',
    posterBg: 'linear-gradient(160deg, #F5F0E8 0%, #FAFAF0 50%, #F5F0E8 100%)',
    headerStyle: 'none',
    accentColor: '#B8960C',
    accentColor2: '#98D8C8',
    textColor: '#5C4800',
    bodyTextColor: '#3A3A2A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '44px',
    headlineWeight: '700',
    headlineEffect: 'serene-gold',
    secondaryColor: '#98D8C8',
    motif: 'buddha',
    headline: 'Happy Buddha Purnima',
    defaultMessage: 'May the teachings of Lord Buddha guide you towards peace, compassion, and enlightenment. Happy Buddha Purnima!',
  },
  {
    id: 'mahavir-jayanti',
    name: 'Mahavir Jayanti',
    festival: 'Mahavir Jayanti',
    posterBg: 'linear-gradient(160deg, #F8F5E8 0%, #FFFDF5 50%, #F8F5E8 100%)',
    headerStyle: 'none',
    accentColor: '#B8860B',
    accentColor2: '#FF6B00',
    textColor: '#5C4400',
    bodyTextColor: '#3A3A1A',
    fontStack: "'Cinzel', Georgia, serif",
    headlineFontSize: '40px',
    headlineWeight: '600',
    headlineEffect: 'serene-gold',
    secondaryColor: '#FF6B00',
    motif: 'mahavir',
    headline: 'Happy Mahavir Jayanti',
    defaultMessage: 'May the teachings of Lord Mahavira — non-violence, truth, and compassion — inspire you to live a life of righteousness. Happy Mahavir Jayanti!',
  },
];

// Event Announcement Templates — Cars24 purple-led (internal announcements)
export const eventAnnouncementTemplates = [
  {
    id: 'festival-celebration',
    name: 'Festival Celebration',
    posterBg: null, // uses BRAND header strip
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF69B4',
    textColor: '#1A1A1A',
    secondaryColor: '#FFD700',
    defaultTitle: 'Festival Celebration',
    defaultDescription: 'Join us for a wonderful celebration as we come together to mark this special occasion with food, fun, and festivities.',
    motif: 'celebration',
  },
  {
    id: 'town-hall',
    name: 'Town Hall',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#4A35FE',
    textColor: '#1A1A1A',
    secondaryColor: '#6B57FF',
    defaultTitle: 'All Hands Town Hall',
    defaultDescription: 'Join us for our quarterly town hall meeting. Hear updates from leadership, celebrate our wins, and ask your questions.',
    motif: 'townhall',
  },
  {
    id: 'rnr-ceremony',
    name: 'R&R Ceremony',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',
    textColor: '#1A1A1A',
    secondaryColor: '#C0C0C0',
    defaultTitle: 'Recognition & Rewards Ceremony',
    defaultDescription: 'Celebrating the outstanding contributors who have gone above and beyond. Join us to honour our stars!',
    motif: 'rnr',
  },
  {
    id: 'hackathon',
    name: 'Hackathon',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#00C9A7',
    textColor: '#1A1A1A',
    secondaryColor: '#00796B',
    defaultTitle: 'Cars24 Hackathon',
    defaultDescription: 'Got a big idea? Bring it to life! Join our hackathon and build solutions that drive the future of Cars24.',
    motif: 'hackathon',
  },
  {
    id: 'wellness-week',
    name: 'Wellness Week',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#6FCF97',
    textColor: '#1A1A1A',
    secondaryColor: '#A8E6CF',
    defaultTitle: 'Wellness Week',
    defaultDescription: 'Your well-being matters. Join us for a week of activities, workshops, and conversations focused on health and happiness.',
    motif: 'wellness',
  },
  {
    id: 'offsite',
    name: 'Offsite',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF8008',
    textColor: '#1A1A1A',
    secondaryColor: '#FFC837',
    defaultTitle: 'Team Offsite',
    defaultDescription: 'Time to step out, connect, and recharge. Join the team for an exciting offsite experience!',
    motif: 'offsite',
  },
  {
    id: 'product-launch',
    name: 'Product Launch',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#00BFFF',
    textColor: '#1A1A1A',
    secondaryColor: '#64B5F6',
    defaultTitle: 'Product Launch',
    defaultDescription: 'We are thrilled to unveil something we have been building. Join us for the big reveal and be among the first to experience it.',
    motif: 'launch',
  },
  {
    id: 'work-anniversary',
    name: 'Work Anniversary',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',
    textColor: '#1A1A1A',
    secondaryColor: '#FF69B4',
    defaultTitle: 'Work Anniversary Celebration',
    defaultDescription: 'Celebrating the milestones of our incredible team members who have been with us through it all.',
    motif: 'anniversary',
  },
];
