// ─── Font stacks ──────────────────────────────────────────────────────────────
// SERIF_ELEGANT  → Playfair Display — Diwali, Eid, Christmas, Good Friday, Buddha
// SERIF_FRAUNCES → Fraunces — Holi, Navratri, Dussehra, Ganesh Chaturthi, Lohri, Baisakhi
// SANS_INTER     → Inter — event announcements, fallback, national days
//
// NOTE: Cinzel, Dancing Script, and Bebas Neue have been removed — they
// do not fit the Cars24 brand. All templates now use Playfair Display,
// Fraunces, or Inter only.

export const FONT_STACKS = {
  SERIF_ELEGANT:  "'Playfair Display', Georgia, 'Times New Roman', serif",
  SERIF_FRAUNCES: "'Fraunces', Georgia, serif",
  SANS_INTER:     "'Inter', 'Segoe UI', system-ui, sans-serif",
};

// ─── Cars24 brand palette ──────────────────────────────────────────────────────
// PRIMARY: #4736FE  PRIMARY_LIGHT: #6B57FF  PRIMARY_LIGHTER: #8B7BFF
// PRIMARY_PALE: #E8E4FF  PRIMARY_DARK: #2E1FCC
// Backgrounds: white / off-white / very pale purple tint
// Festival accents are used ONLY inside motif SVGs (30% of motif, not backgrounds)

// Festival Wishes Templates
export const festivalWishTemplates = [
  {
    id: 'diwali',
    name: 'Diwali',
    festival: 'Diwali',
    // White/pale-purple background — Cars24 brand
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #F0EEFF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — diya base, borders
    accentColor2: '#D4A017',      // Gold — festival accent (diya flame only)
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '52px',
    headlineWeight: '800',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'diwali',
    headline: '✦ Happy Diwali ✦',
    defaultMessage: 'Wishing you and your loved ones a festival full of light, joy, and prosperity. May this Diwali illuminate your life with happiness and success.',
  },
  {
    id: 'holi',
    name: 'Holi',
    festival: 'Holi',
    posterBg: 'linear-gradient(145deg, #FAFAFF 0%, #F4F0FF 60%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — dominant splash colour
    accentColor2: '#E91E8C',      // Magenta — festival accent (30% of splashes)
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '58px',
    headlineWeight: '900',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'holi',
    headline: 'Happy Holi',
    defaultMessage: 'May the colours of Holi fill your life with joy, laughter, and endless happiness. Wishing you a vibrant and colourful celebration!',
  },
  {
    id: 'eid-ul-fitr',
    name: 'Eid-ul-Fitr',
    festival: 'Eid-ul-Fitr',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — crescent, borders
    accentColor2: '#C9A23C',      // Gold star — festival accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '48px',
    headlineWeight: '700',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'eid',
    headline: 'Eid Mubarak',
    defaultMessage: 'May this auspicious occasion of Eid bring peace, happiness, and prosperity to you and your family. Eid Mubarak!',
  },
  {
    id: 'eid-al-adha',
    name: 'Eid-al-Adha',
    festival: 'Eid-al-Adha',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',
    accentColor2: '#C9A23C',
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '42px',
    headlineWeight: '700',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'eid',
    headline: 'Eid al-Adha Mubarak',
    defaultMessage: 'On this blessed occasion of Eid al-Adha, may Allah bless you with happiness, peace, and prosperity. Wishing you and your family a joyful celebration.',
  },
  {
    id: 'christmas',
    name: 'Christmas',
    festival: 'Christmas',
    posterBg: 'linear-gradient(170deg, #FAFAFF 0%, #F2EEFF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — most snowflakes, pine
    accentColor2: '#C62828',      // Christmas red — berry accents only
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '50px',
    headlineWeight: '800',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'christmas',
    headline: 'Merry Christmas',
    defaultMessage: 'Wishing you the warmth of family, the joy of friends, and the best of everything this Christmas and throughout the coming year.',
  },
  {
    id: 'new-year',
    name: 'New Year',
    festival: 'New Year',
    posterBg: 'linear-gradient(145deg, #FAFAFF 0%, #EDE8FF 55%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — fireworks, confetti
    accentColor2: '#D4A017',      // Gold — champagne accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '58px',
    headlineWeight: '800',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'newyear',
    headline: 'Happy New Year',
    defaultMessage: 'Cheers to new beginnings, bigger dreams, and brighter days ahead. Wishing you a wonderful New Year filled with joy and success!',
  },
  {
    id: 'independence-day',
    name: 'Independence Day',
    festival: 'Independence Day',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — Chakra, borders
    accentColor2: '#FF8F00',      // Saffron — tricolour accent only
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '40px',
    headlineWeight: '800',
    headlineEffect: 'brand-purple',
    secondaryColor: '#138808',    // Green — third tricolour stripe
    motif: 'independence',
    headline: 'Happy Independence Day',
    defaultMessage: 'Wishing you a proud and joyful Independence Day. Let us honour the spirit of freedom and unity that defines our great nation.',
  },
  {
    id: 'republic-day',
    name: 'Republic Day',
    festival: 'Republic Day',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 60%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',
    accentColor2: '#FF8F00',
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '38px',
    headlineWeight: '800',
    headlineEffect: 'brand-purple',
    secondaryColor: '#138808',
    motif: 'republic',
    headline: 'Happy Republic Day',
    defaultMessage: 'On this day we celebrate the strength of our democracy and the values enshrined in our Constitution. Happy Republic Day!',
  },
  {
    id: 'raksha-bandhan',
    name: 'Raksha Bandhan',
    festival: 'Raksha Bandhan',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #F0EEFF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — rakhi, floral corners
    accentColor2: '#D4851A',      // Saffron thread — festival accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '44px',
    headlineWeight: '700',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'rakhi',
    headline: 'Happy Raksha Bandhan',
    defaultMessage: 'May the bond of love, care, and protection between brothers and sisters grow stronger with every passing year. Happy Raksha Bandhan!',
  },
  {
    id: 'ganesh-chaturthi',
    name: 'Ganesh Chaturthi',
    festival: 'Ganesh Chaturthi',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — Om, border, marigolds
    accentColor2: '#D4851A',      // Saffron — marigold accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '40px',
    headlineWeight: '900',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'ganesh',
    headline: 'Happy Ganesh Chaturthi',
    defaultMessage: 'May Lord Ganesha bless you with wisdom, prosperity, and the removal of all obstacles from your path. Ganpati Bappa Morya!',
  },
  {
    id: 'dussehra',
    name: 'Dussehra',
    festival: 'Dussehra',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',
    accentColor2: '#D4851A',      // Saffron flame accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '52px',
    headlineWeight: '900',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'dussehra',
    headline: 'Happy Dussehra',
    defaultMessage: 'May this Dussehra mark the victory of good over evil in your life. Wishing you strength, courage, and triumph in everything you do.',
  },
  {
    id: 'navratri',
    name: 'Navratri',
    festival: 'Navratri',
    posterBg: 'linear-gradient(135deg, #F0EEFF 0%, #E8E4FF 50%, #F0EEFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — primary motif
    accentColor2: '#E91E8C',      // Magenta — festival accent (dandiya pops)
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '54px',
    headlineWeight: '900',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'navratri',
    headline: 'Happy Navratri',
    defaultMessage: 'May Goddess Durga bless you with her divine grace, strength, and happiness during this auspicious festival. Happy Navratri!',
  },
  {
    id: 'onam',
    name: 'Onam',
    festival: 'Onam',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #F0EEFF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — pookalam flowers, border
    accentColor2: '#D4851A',      // Warm gold — festival accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '54px',
    headlineWeight: '700',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'onam',
    headline: 'Happy Onam',
    defaultMessage: 'Wishing you the blessings of prosperity, peace, and happiness on this harvest festival. May Onam bring joy and togetherness!',
  },
  {
    id: 'pongal',
    name: 'Pongal',
    festival: 'Pongal',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — kolam, border
    accentColor2: '#D4851A',      // Amber — pongal pot / harvest accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '54px',
    headlineWeight: '700',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'pongal',
    headline: 'Happy Pongal',
    defaultMessage: 'On this auspicious harvest festival, may your life overflow with joy, abundance, and good fortune. Wishing you a very Happy Pongal!',
  },
  {
    id: 'baisakhi',
    name: 'Baisakhi',
    festival: 'Baisakhi',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — khanda, border
    accentColor2: '#D4A017',      // Wheat gold — harvest accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '54px',
    headlineWeight: '900',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'baisakhi',
    headline: 'Happy Baisakhi',
    defaultMessage: 'May the harvest festival of Baisakhi bring you prosperity, happiness, and the spirit of celebration. Wishing you a joyful Baisakhi!',
  },
  {
    id: 'lohri',
    name: 'Lohri',
    festival: 'Lohri',
    posterBg: 'linear-gradient(160deg, #F4F0FF 0%, #E8E4FF 50%, #F4F0FF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — border, dots
    accentColor2: '#FF6D00',      // Fire orange — flame accent only
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Fraunces', Georgia, serif",
    headlineFontSize: '56px',
    headlineWeight: '900',
    headlineEffect: 'brand-purple',
    secondaryColor: '#D4A017',    // Gold — ember accent
    motif: 'lohri',
    headline: 'Happy Lohri',
    defaultMessage: 'May the warmth of the Lohri bonfire fill your life with happiness, love, and good health. Wishing you and your family a wonderful Lohri!',
  },
  {
    id: 'gurpurab',
    name: 'Gurpurab',
    festival: 'Gurpurab',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — Khanda, lanterns, border
    accentColor2: '#D4A017',      // Gold — festival accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '46px',
    headlineWeight: '600',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'gurpurab',
    headline: 'Happy Gurpurab',
    defaultMessage: 'On this sacred occasion of Gurpurab, may the teachings of Guru Nanak Dev Ji inspire you to live a life of compassion, service, and devotion. Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh!',
  },
  {
    id: 'good-friday',
    name: 'Good Friday',
    festival: 'Good Friday',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 60%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — cross, floral
    accentColor2: '#8B7BFF',      // Purple lighter — serene variation
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '46px',
    headlineWeight: '700',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'goodfriday',
    headline: 'Good Friday',
    defaultMessage: 'On this solemn day, may you find peace, reflection, and hope. Wishing you a meaningful Good Friday.',
  },
  {
    id: 'buddha-purnima',
    name: 'Buddha Purnima',
    festival: 'Buddha Purnima',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #F0EEFF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — lotus, dharma wheel
    accentColor2: '#D4A017',      // Serene gold — inner lotus accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '44px',
    headlineWeight: '700',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'buddha',
    headline: 'Happy Buddha Purnima',
    defaultMessage: 'May the teachings of Lord Buddha guide you towards peace, compassion, and enlightenment. Happy Buddha Purnima!',
  },
  {
    id: 'mahavir-jayanti',
    name: 'Mahavir Jayanti',
    festival: 'Mahavir Jayanti',
    posterBg: 'linear-gradient(160deg, #FAFAFF 0%, #EEE8FF 50%, #FAFAFF 100%)',
    headerStyle: 'none',
    accentColor: '#4736FE',       // Cars24 purple — Jain hand, border
    accentColor2: '#D4A017',      // Gold — serene accent
    textColor: '#4736FE',
    bodyTextColor: '#4A4A4A',
    fontStack: "'Playfair Display', Georgia, serif",
    headlineFontSize: '40px',
    headlineWeight: '600',
    headlineEffect: 'brand-purple',
    secondaryColor: '#6B57FF',
    motif: 'mahavir',
    headline: 'Happy Mahavir Jayanti',
    defaultMessage: 'May the teachings of Lord Mahavira — non-violence, truth, and compassion — inspire you to live a life of righteousness. Happy Mahavir Jayanti!',
  },
];

// Event Announcement Templates — Cars24 purple-led (internal announcements)
export const eventAnnouncementTemplates = [
  {
    id: 'festival-celebration',
    name: 'Festival Celebration',
    posterBg: null, // uses BRAND header strip
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4736FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF69B4',
    textColor: '#1A1A1A',
    secondaryColor: '#FFD700',
    defaultTitle: 'Festival Celebration',
    defaultDescription: 'Join us for a wonderful celebration as we come together to mark this special occasion with food, fun, and festivities.',
    motif: 'celebration',
  },
  {
    id: 'town-hall',
    name: 'Town Hall',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4736FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#4736FE',
    textColor: '#1A1A1A',
    secondaryColor: '#6B57FF',
    defaultTitle: 'All Hands Town Hall',
    defaultDescription: 'Join us for our quarterly town hall meeting. Hear updates from leadership, celebrate our wins, and ask your questions.',
    motif: 'townhall',
  },
  {
    id: 'rnr-ceremony',
    name: 'R&R Ceremony',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4736FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',
    textColor: '#1A1A1A',
    secondaryColor: '#C0C0C0',
    defaultTitle: 'Recognition & Rewards Ceremony',
    defaultDescription: 'Celebrating the outstanding contributors who have gone above and beyond. Join us to honour our stars!',
    motif: 'rnr',
  },
  {
    id: 'hackathon',
    name: 'Hackathon',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4736FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#00C9A7',
    textColor: '#1A1A1A',
    secondaryColor: '#00796B',
    defaultTitle: 'Cars24 Hackathon',
    defaultDescription: 'Got a big idea? Bring it to life! Join our hackathon and build solutions that drive the future of Cars24.',
    motif: 'hackathon',
  },
  {
    id: 'wellness-week',
    name: 'Wellness Week',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4736FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#6FCF97',
    textColor: '#1A1A1A',
    secondaryColor: '#A8E6CF',
    defaultTitle: 'Wellness Week',
    defaultDescription: 'Your well-being matters. Join us for a week of activities, workshops, and conversations focused on health and happiness.',
    motif: 'wellness',
  },
  {
    id: 'offsite',
    name: 'Offsite',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4736FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF8008',
    textColor: '#1A1A1A',
    secondaryColor: '#FFC837',
    defaultTitle: 'Team Offsite',
    defaultDescription: 'Time to step out, connect, and recharge. Join the team for an exciting offsite experience!',
    motif: 'offsite',
  },
  {
    id: 'product-launch',
    name: 'Product Launch',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4736FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#00BFFF',
    textColor: '#1A1A1A',
    secondaryColor: '#64B5F6',
    defaultTitle: 'Product Launch',
    defaultDescription: 'We are thrilled to unveil something we have been building. Join us for the big reveal and be among the first to experience it.',
    motif: 'launch',
  },
  {
    id: 'work-anniversary',
    name: 'Work Anniversary',
    posterBg: null,
    headerStyle: 'brand',
    gradient: 'linear-gradient(135deg, #4736FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',
    textColor: '#1A1A1A',
    secondaryColor: '#FF69B4',
    defaultTitle: 'Work Anniversary Celebration',
    defaultDescription: 'Celebrating the milestones of our incredible team members who have been with us through it all.',
    motif: 'anniversary',
  },
];
