// Festival Wishes Templates
// Brand palette: Primary #4A35FE · Light #6B57FF · Dark #2E1FCC · BG #FFFFFF
// accentColor = festival-specific motif colour only (used solely in SVG motif + thin divider)
// gradient / bgColor / textColor drive the Cars24 white-forward layout in PosterCanvas

export const festivalWishTemplates = [
  {
    id: 'diwali',
    name: 'Diwali',
    festival: 'Diwali',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#F5C518',       // gold — used only in diya motif & divider
    textColor: '#1A1A1A',
    secondaryColor: '#F5C518',
    headline: 'Happy Diwali',
    defaultMessage: 'Wishing you and your loved ones a festival full of light, joy, and prosperity. May this Diwali illuminate your life with happiness and success.',
    motif: 'diwali',
  },
  {
    id: 'holi',
    name: 'Holi',
    festival: 'Holi',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF6B00',       // orange — used only in splash motif
    textColor: '#1A1A1A',
    secondaryColor: '#FF1493',
    headline: 'Happy Holi',
    defaultMessage: 'May the colours of Holi fill your life with joy, laughter, and endless happiness. Wishing you a vibrant and colourful celebration!',
    motif: 'holi',
  },
  {
    id: 'eid-ul-fitr',
    name: 'Eid-ul-Fitr',
    festival: 'Eid-ul-Fitr',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#D4AF37',       // gold — used only in crescent/star motif
    textColor: '#1A1A1A',
    secondaryColor: '#D4AF37',
    headline: 'Eid Mubarak',
    defaultMessage: 'May this auspicious occasion of Eid bring peace, happiness, and prosperity to you and your family. Eid Mubarak!',
    motif: 'eid',
  },
  {
    id: 'eid-al-adha',
    name: 'Eid-al-Adha',
    festival: 'Eid-al-Adha',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#C9A84C',       // antique gold — used only in motif
    textColor: '#1A1A1A',
    secondaryColor: '#C9A84C',
    headline: 'Eid al-Adha Mubarak',
    defaultMessage: 'On this blessed occasion of Eid al-Adha, may Allah bless you with happiness, peace, and prosperity. Wishing you and your family a joyful celebration.',
    motif: 'eid',
  },
  {
    id: 'christmas',
    name: 'Christmas',
    festival: 'Christmas',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#C41E3A',       // Christmas red — used only in snowflake/holly motif
    textColor: '#1A1A1A',
    secondaryColor: '#C41E3A',
    headline: 'Merry Christmas',
    defaultMessage: 'Wishing you the warmth of family, the joy of friends, and the best of everything this Christmas and throughout the coming year.',
    motif: 'christmas',
  },
  {
    id: 'new-year',
    name: 'New Year',
    festival: 'New Year',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',       // gold — fireworks motif
    textColor: '#1A1A1A',
    secondaryColor: '#C0C0C0',
    headline: 'Happy New Year',
    defaultMessage: 'Cheers to new beginnings, bigger dreams, and brighter days ahead. Wishing you a wonderful New Year filled with joy and success!',
    motif: 'newyear',
  },
  {
    id: 'independence-day',
    name: 'Independence Day',
    festival: 'Independence Day',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF9933',       // saffron — Ashoka chakra motif
    textColor: '#1A1A1A',
    secondaryColor: '#138808',
    headline: 'Happy Independence Day',
    defaultMessage: 'Wishing you a proud and joyful Independence Day. Let us honour the spirit of freedom and unity that defines our great nation.',
    motif: 'independence',
  },
  {
    id: 'republic-day',
    name: 'Republic Day',
    festival: 'Republic Day',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF9933',       // saffron — chakra motif
    textColor: '#1A1A1A',
    secondaryColor: '#138808',
    headline: 'Happy Republic Day',
    defaultMessage: 'On this day we celebrate the strength of our democracy and the values enshrined in our Constitution. Happy Republic Day!',
    motif: 'independence',
  },
  {
    id: 'raksha-bandhan',
    name: 'Raksha Bandhan',
    festival: 'Raksha Bandhan',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF69B4',       // pink — rakhi medallion motif
    textColor: '#1A1A1A',
    secondaryColor: '#FF69B4',
    headline: 'Happy Raksha Bandhan',
    defaultMessage: 'May the bond of love, care, and protection between brothers and sisters grow stronger with every passing year. Happy Raksha Bandhan!',
    motif: 'rakhi',
  },
  {
    id: 'ganesh-chaturthi',
    name: 'Ganesh Chaturthi',
    festival: 'Ganesh Chaturthi',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF8C00',       // marigold orange — Om & marigold motif
    textColor: '#1A1A1A',
    secondaryColor: '#FFD700',
    headline: 'Happy Ganesh Chaturthi',
    defaultMessage: 'May Lord Ganesha bless you with wisdom, prosperity, and the removal of all obstacles from your path. Ganpati Bappa Morya!',
    motif: 'ganesh',
  },
  {
    id: 'dussehra',
    name: 'Dussehra',
    festival: 'Dussehra',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF4500',       // vermilion — bow & flame motif
    textColor: '#1A1A1A',
    secondaryColor: '#FFD700',
    headline: 'Happy Dussehra',
    defaultMessage: 'May this Dussehra mark the victory of good over evil in your life. Wishing you strength, courage, and triumph in everything you do.',
    motif: 'dussehra',
  },
  {
    id: 'navratri',
    name: 'Navratri',
    festival: 'Navratri',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#CC0066',       // deep pink — dandiya/mandala motif
    textColor: '#1A1A1A',
    secondaryColor: '#FF6B00',
    headline: 'Happy Navratri',
    defaultMessage: 'May Goddess Durga bless you with her divine grace, strength, and happiness during this auspicious festival. Happy Navratri!',
    motif: 'navratri',
  },
  {
    id: 'onam',
    name: 'Onam',
    festival: 'Onam',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',       // gold — pookalam motif
    textColor: '#1A1A1A',
    secondaryColor: '#228B22',
    headline: 'Happy Onam',
    defaultMessage: 'Wishing you the blessings of prosperity, peace, and happiness on this harvest festival. May Onam bring joy and togetherness!',
    motif: 'onam',
  },
  {
    id: 'pongal',
    name: 'Pongal',
    festival: 'Pongal',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF6B00',       // orange — pongal pot motif
    textColor: '#1A1A1A',
    secondaryColor: '#FFD700',
    headline: 'Happy Pongal',
    defaultMessage: 'On this auspicious harvest festival, may your life overflow with joy, abundance, and good fortune. Wishing you a very Happy Pongal!',
    motif: 'pongal',
  },
  {
    id: 'baisakhi',
    name: 'Baisakhi',
    festival: 'Baisakhi',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',       // gold — wheat/khanda motif
    textColor: '#1A1A1A',
    secondaryColor: '#FF6B00',
    headline: 'Happy Baisakhi',
    defaultMessage: 'May the harvest festival of Baisakhi bring you prosperity, happiness, and the spirit of celebration. Wishing you a joyful Baisakhi!',
    motif: 'baisakhi',
  },
  {
    id: 'lohri',
    name: 'Lohri',
    festival: 'Lohri',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF4500',       // fire orange — bonfire motif
    textColor: '#1A1A1A',
    secondaryColor: '#FFD700',
    headline: 'Happy Lohri',
    defaultMessage: 'May the warmth of the Lohri bonfire fill your life with happiness, love, and good health. Wishing you and your family a wonderful Lohri!',
    motif: 'lohri',
  },
  {
    id: 'gurpurab',
    name: 'Gurpurab',
    festival: 'Gurpurab',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF8C00',       // amber — Ik Onkar / lantern motif
    textColor: '#1A1A1A',
    secondaryColor: '#FFD700',
    headline: 'Happy Gurpurab',
    defaultMessage: 'On this sacred occasion of Gurpurab, may the teachings of Guru Nanak Dev Ji inspire you to live a life of compassion, service, and devotion. Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh!',
    motif: 'gurpurab',
  },
  {
    id: 'good-friday',
    name: 'Good Friday',
    festival: 'Good Friday',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#8B7355',       // warm taupe — cross/olive motif
    textColor: '#1A1A1A',
    secondaryColor: '#8B7355',
    headline: 'Good Friday',
    defaultMessage: 'On this solemn day, may you find peace, reflection, and hope. Wishing you a meaningful Good Friday.',
    motif: 'goodfriday',
  },
  {
    id: 'buddha-purnima',
    name: 'Buddha Purnima',
    festival: 'Buddha Purnima',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',       // gold — lotus motif
    textColor: '#1A1A1A',
    secondaryColor: '#98D8C8',
    headline: 'Happy Buddha Purnima',
    defaultMessage: 'May the teachings of Lord Buddha guide you towards peace, compassion, and enlightenment. Happy Buddha Purnima!',
    motif: 'buddha',
  },
  {
    id: 'mahavir-jayanti',
    name: 'Mahavir Jayanti',
    festival: 'Mahavir Jayanti',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF8C00',       // amber — Jain symbol motif
    textColor: '#1A1A1A',
    secondaryColor: '#FF6B00',
    headline: 'Happy Mahavir Jayanti',
    defaultMessage: 'May the teachings of Lord Mahavira — non-violence, truth, and compassion — inspire you to live a life of righteousness. Happy Mahavir Jayanti!',
    motif: 'mahavir',
  },
];

// Event Announcement Templates
// Same Cars24-first approach: white body, purple header strip, festival accent only in motif
export const eventAnnouncementTemplates = [
  {
    id: 'festival-celebration',
    name: 'Festival Celebration',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF69B4',       // pink — confetti/balloon motif
    textColor: '#1A1A1A',
    secondaryColor: '#FFD700',
    defaultTitle: 'Festival Celebration',
    defaultDescription: 'Join us for a wonderful celebration as we come together to mark this special occasion with food, fun, and festivities.',
    motif: 'celebration',
  },
  {
    id: 'town-hall',
    name: 'Town Hall',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#4A35FE',       // brand purple — mic/grid motif (consistent)
    textColor: '#1A1A1A',
    secondaryColor: '#6B57FF',
    defaultTitle: 'All Hands Town Hall',
    defaultDescription: 'Join us for our quarterly town hall meeting. Hear updates from leadership, celebrate our wins, and ask your questions.',
    motif: 'townhall',
  },
  {
    id: 'rnr-ceremony',
    name: 'R&R Ceremony',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',       // gold — trophy/stars motif
    textColor: '#1A1A1A',
    secondaryColor: '#C0C0C0',
    defaultTitle: 'Recognition & Rewards Ceremony',
    defaultDescription: 'Celebrating the outstanding contributors who have gone above and beyond. Join us to honour our stars!',
    motif: 'rnr',
  },
  {
    id: 'hackathon',
    name: 'Hackathon',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#00C9A7',       // teal — code/circuit motif
    textColor: '#1A1A1A',
    secondaryColor: '#00796B',
    defaultTitle: 'Cars24 Hackathon',
    defaultDescription: 'Got a big idea? Bring it to life! Join our hackathon and build solutions that drive the future of Cars24.',
    motif: 'hackathon',
  },
  {
    id: 'wellness-week',
    name: 'Wellness Week',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#6FCF97',       // leaf green — heart/leaf motif
    textColor: '#1A1A1A',
    secondaryColor: '#A8E6CF',
    defaultTitle: 'Wellness Week',
    defaultDescription: 'Your well-being matters. Join us for a week of activities, workshops, and conversations focused on health and happiness.',
    motif: 'wellness',
  },
  {
    id: 'offsite',
    name: 'Offsite',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FF8008',       // amber — mountain/sun motif
    textColor: '#1A1A1A',
    secondaryColor: '#FFC837',
    defaultTitle: 'Team Offsite',
    defaultDescription: 'Time to step out, connect, and recharge. Join the team for an exciting offsite experience!',
    motif: 'offsite',
  },
  {
    id: 'product-launch',
    name: 'Product Launch',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#00BFFF',       // electric blue — rocket/stars motif
    textColor: '#1A1A1A',
    secondaryColor: '#64B5F6',
    defaultTitle: 'Product Launch',
    defaultDescription: 'We are thrilled to unveil something we have been building. Join us for the big reveal and be among the first to experience it.',
    motif: 'launch',
  },
  {
    id: 'work-anniversary',
    name: 'Work Anniversary',
    gradient: 'linear-gradient(135deg, #4A35FE 0%, #6B57FF 100%)',
    bgColor: '#FFFFFF',
    accentColor: '#FFD700',       // gold — ribbon/stars motif
    textColor: '#1A1A1A',
    secondaryColor: '#FF69B4',
    defaultTitle: 'Work Anniversary Celebration',
    defaultDescription: 'Celebrating the milestones of our incredible team members who have been with us through it all.',
    motif: 'anniversary',
  },
];
